name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Emacs
        uses: jcs090218/setup-emacs@master
        with:
          version: '30.1'

      - name: Install Eldev
        uses: emacs-eldev/setup-eldev@v1

      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Byte-compile with warnings as errors
        run: eldev -dtT -C compile --set all --warnings-as-errors

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version: ['28.2', '29.4', '30.1']
    steps:
      - name: Set up Emacs
        uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Install Eldev
        uses: emacs-eldev/setup-eldev@v1

      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Run tests
        run: eldev -p -dtT -C test
